### ISSUE TITLE
Telescope / Instrument names

### ISSUE THREAD

**Issue by astro-mf** [Astro-Sean/autophot#1]
Make sure that telescope+instrument is used as identifier in yaml to avoid situations where there are multiple instruments on one telescope

**Comment by Astro-Sean** [comment]
call_database.py now now has nested dictionary structure: To allow for different instrument from the same telescope. If we use the example of the NTT with EFOSC and SOFI mount the structure would be:
ESO-NTT:
    INSTRUME:
        EFOSC:
            - filter keyword
            - gain keyword 
            - ....etc
        SOFI:
            - filter keyword
            - gain keyword 
            - ....etc

For further example check: https://github.com/Astro-Sean/autophot/blob/master/example_call_database.ipynb
