### ISSUE TITLE
Error while installing AutoPhOT using conda

### ISSUE THREAD

**Issue by navii98** [Astro-Sean/autophot#1]
Hi Sean, I tried to install AutoPHoT using conda on two of my linux machines (one running on fedora and other on ubuntu). 
And I'm getting a similar error in on both during the installation.

In the fedora machine - 
> (autophot) [navii@fedora ~]$ conda install -c astro-sean AutoPhOT
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: \
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.34=0
>   - feature:|@/linux-64::__glibc==2.34=0
> 
> Your installed version is: 2.34

And in the ubuntu machine - 
> ❯ conda install -c astro-sean AutoPhOT                                               
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: -
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.33=0
>   - feature:|@/linux-64::__glibc==2.33=0
> 
> Your installed version is: 2.33

I was hoping if you could help me resolve this.

**Comment by Astro-Sean** [comment]
Looking into this!- Will report back shortly!!

**Comment by Astro-Sean** [comment]
Hi again, 

I managed to reproduce the error for a ubuntu  system running on a virtual machine. 

This error seems to be due to packages clashing with conda-forge and astropy channls. 

Can you make sure these are accessible in the channel lists? So in your autophot_env can you run: 

```
conda config --show channels
```

If you don't see conda-forge and/or astropy can you run:

```
conda config --append channels conda-forge
conda config --append channels astropy
```

and then try the install again:

```
conda install -c astro-sean autophot
```

By performing the above I was successfully able to import autophot in a python script. Let me know how it goes!!

**Comment by navii98** [comment]
Cheers! Adding the `conda-forge` and `astropy` channels solved the issue. I was able to successfully install AutoPhOT after that. Thanks, for the quick response. I guess you can close this issue now.

This is a very interesting project and something I believe will be very useful for the community. What is your preferred method of communication for questions and discussions related to this project.

**Comment by Astro-Sean** [comment]
Brilliant! 

Depends on the topic - for bugs, bad user experience, bad science (if any) and/or installation/execution issues - best to open an issue. 

Also open an issue if you need some help (i.e. a tutorial notebook) on how to perform a certain task with the code, how to deal with an annoying scenario etc. 

For anything more "long term" i.e. adding new features, packages, or functionality -  probably best to shoot me an email!
