### ISSUE TITLE
small problem

### ISSUE THREAD

**Issue by Yanshengyu0311** [Astro-Sean/autophot#11]
Hi Sean,
  In your [autophot/packages/template_subtraction.py] function subtract,
  your pipeline is:
  HOTPANTS_log = write_dir + base + '_HOTterPANTS.txt'
  I think 
  HOTPANTS_log = os.path.join(write_dir , base + '_HOTterPANTS.txt')
  or
  HOTPANTS_log = write_dir +'/'+ base + '_HOTterPANTS.txt'
  will makes the XXX_REDUCED file more concise!

**Comment by Astro-Sean** [comment]
Hi,

Thanks for your issue  -  I actually spotted this during the week and I'll patch soon!
