### ISSUE TITLE
cosmic ray removal may cause the templates value risk

### ISSUE THREAD

**Issue by Yanshengyu0311** [Astro-Sean/autophot#12]
Hi Sean，
When invoking the prepare_templates, the remove_cosmic_rays may cause GAIN times image value. If the template values if large or running prepare_templates many times, and the gain is larger than one, it may cause the new template fits value larger than 2^16. 
```
from autophot.packages.call_crayremoval import remove_cosmic_rays
from astropy.io import fits

image=fits.getdata(image_path)
image_old = fits.PrimaryHDU(image)

remove_cosmic_rays(image_old,gain = 1.9, use_lacosmic = False) / image
```

![Screenshot_2022-04-12_18-11-43](https://user-images.githubusercontent.com/54763954/162939332-9fb0f503-c533-4273-88e0-2e3fcdf9d0ab.png)
In the step subtracting template, hotpants need an upper limit of a template value, 

        if  remove_sat  :

            image_max = [np.nanmax(check_values_image) if np.nanmax(check_values_image) < 2**16 else  + 2**16][0]

            template_max = [np.nanmax(check_values_template) if np.nanmax(check_values_template) < 2**16 else  2**16][0]

        else:

            image_max = np.nanmax(check_values_image)

            template_max = np.nanmax(np.nanmax(check_values_template))

The temple_max is 2**16, which may induce the hotpants subtraction to fail.
I think adding this step in call_crayremoval.py before returning the result could be better:

```
clean_image=clean_image/gain

return clean_image
```
My English is poor, If I didn't make you understand, I will give you a more detailed description.

**Comment by Astro-Sean** [comment]
Hi - sorry for the delay I am only coming back to the code now - Your suggestion is perfectly valid and I'll implement the fix in the next release!
