### ISSUE TITLE
AutoPhOT Installation Issue

### ISSUE THREAD

**Issue by RustinFibber** [Astro-Sean/autophot#15]
Hello Sean!
I've been trying to install AutoPhOT on my Ubuntu (22.04 LTS) system. I followed your advice in the other Issue opened by @navii98 and added the `conda-forge` and `astropy` channels. But when I hit the command `conda install -c astro-sean AutoPhOT` the following stuff was dumped in my terminal:
![Screenshot from 2022-07-11 16-31-58](https://user-images.githubusercontent.com/90977060/178254039-49e6f0be-44c3-4fc9-8673-a3e288945515.png)
And after some time the terminal closed on its own without installation. This has happened every time I tried to install. I'd really appreciate your help in solving this issue!

**Comment by Astro-Sean** [comment]
Hi,

Can you try running:

`conda install -c astro-sean autophot`

All lowercase unlike what you have above - hopefully this fixes things!

**Comment by RustinFibber** [comment]
Unfortunately, I already tried the lowercase version several times. I tried it once again after your reply. It still doesn't seem to work :(
![Screenshot from 2022-07-11 23-06-12](https://user-images.githubusercontent.com/90977060/178324870-8413ddb1-7ffb-47b2-aed3-9d42efce69da.png)

**Comment by Astro-Sean** [comment]
Hmmmmm not too sure what is the issue without futher details but something we can try ....

I find conda install can be quite strict when installing packages - a alternative is using mamba so to inistall it in the autophot_env

`
conda install mamba -c conda-forge
`

and then try 

`
mamba install -c astro-sean autophot
`

**Comment by RustinFibber** [comment]
Hi Sean, 

It finally worked! I had to reinstall Anaconda and followed your instructions once again. Thanks a lot for your help!

**Comment by Astro-Sean** [comment]
Ah great to hear - some users are having some issues installing the code and I think this is just package discrepancies in conda - Enjoy using the code - I will close this issue
