### ISSUE TITLE
Custom catalogue

### ISSUE THREAD

**Issue by pjpessi** [Astro-Sean/autophot#17]
Hi Sean,

I am trying this amazing tool you've develop and I run into a small issue, I hope you can help me sort it out.
I want to use the RefCat2 catalog (it has every catalogue inside) so I selected
`autophot_input['catalog']['use_catalog'] = 'custom'`
To get the catalog I then used
`jobs = mastcasjobs.MastCasJobs(userid=wsid, password=pwd, 
                                   context="HLSP_ATLAS_REFCAT2")`
This returns a pandas dataframe, so really there is no need for me to print the result out in a file. Hence, I didn't indicate a catalog path. The issue is that I get the following error:

` 

> if not autophot_input['catalog']['catalog_custom_fpath']:
>   logger.critical('Custom catalog selected but "catalog_custom_fpath" not defined')
> -->  exit()
>    else:
>    fname = autophot_input['catalog']['catalog_custom_fpath']
> 
> NameError: name 'exit' is not defined

`

Is there a way to not write out my catalog? Or do I definitely need to do it and to indicate a catalog path?

Thanks a lot in advance

**Comment by Astro-Sean** [comment]
Hej!

So I'm afraid with the current build the catalog is read in from file each time the loop is perfrmed, meaning yes you will need to write that dataframe to file (with the correct column headers)...

**Comment by pjpessi** [comment]
Ok, good to know. Thanks!
