### ISSUE TITLE
Filters Not Included 

### ISSUE THREAD

**Issue by B-War** [Astro-Sean/autophot#19]
I'm trying to run AutoPhot on a collection of fits however I keep getting the following:

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        _       _       ___ _  _    _____
       /_\ _  _| |_ ___| _ \ || |__|_   _|
      / _ \ || |  _/ _ \  _/ __ / _ \| |
     /_/ \_\_,_|\__\___/_| |_||_\___/|_|
    
     ---------------------------------------
        Automated Photometry of Transients
        S. J. Brennan et al. 2021 
        Please provide feedback/bugs to:
        Email: sean.brennan2@ucdconnect.ie
    ---------------------------------------
Directory of fits file: /home/ben/Python/pt5m/SN2107eaw/Processed
Found Telescopes:

 - pt5m

-> Telescope check complete

Checking Filter keywords and database

-> Filter check complete

Checking Filter information for each image

Files removed - Wrong Image Type: 0

Files removed - No/Wrong filter(s): 2283
Filters not included: [B, I, R, V]

Files removed: 2283

---

Files that failed : []

DONE

Done - Time Taken: 55.3
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The bit I'm not understanding is why it is saying filters not included are B, I, R, and V when I though these were options? For additional information in my fits they are label as FILTER, and the B,V,R, and I correspond to Johnson-Cousins filters.

**Comment by WangBrad** [comment]
Encountering same problem, how's that solved?
