### ISSUE TITLE
KeyError:['nyquist_limit']

### ISSUE THREAD

**Issue by deckersm** [Astro-Sean/autophot#7]
Hi Sean, 

Thanks for creating this, it's incredibly helpful! 

I just ran into a KeyError on ['nyquist_limit'] and checked main.py. You call this:

            if image_fwhm < autophot_input['photometry']['nyquist_limit'] and autophot_input['photometry']['check_nyquist']:
                logging.warning('\nFWHM [%.1f]<%.1f - Sampling errors - using aperture Photometry' % (image_fwhm,autophot_input['nyquist_limit']))

And I think instead of autophot_input['nyquist_limit'] it should be autophot_input['photometry']['nyquist_limit']. At least, I made that change locally and it seems to have fixed the problem.

Cheers,
Maxime

**Comment by Astro-Sean** [comment]
Hi Maxime,

Yes you are correct - this is a remnant of the old input structure.

Thanks for raising the issue, I have fixed this in V1.0.4.

**Comment by Astro-Sean** [comment]
I will leave this issue open for those who encounter it with V1.0.3 .
