### ISSUE TITLE
KeyError:['trim_edges_pixels']

### ISSUE THREAD

**Issue by Yanshengyu0311** [Astro-Sean/autophot#9]
Hi Sean,
  I just found a KeyError:
  in main.py line 365:

            logging.info('\nTrimming edges of image by +/- %d pixels' % autophot_input['trim_edges_pixels'])

for parameter
autophot_input['trim_edges_pixels']
I think it should be:
autophot_input['preprocessing']['trim_edges_pixels']

I think it's the same problem as Maxime

Cheers
Shengyu

**Comment by Astro-Sean** [comment]
Hi Shengyu,

Yes you are correct - this is a remnant of an old input structure - I will correct this in v1.0.6

**Comment by Astro-Sean** [comment]
V1.0.6 is now on Conda
